import 'bootstrap/dist/css/bootstrap.css';
import '../../styles/globals.css'
import Header from '@/components/Header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="noindex, nofollow" />
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
